export const orderData = [
  // {
  //   id: 147,
  //   name: "Chicken",
  //   amount: 3,
  //   price: 249,
  //   type: "non-veg",
  //   cuisine: "South-Indian",
  //   orderDate: new Date("2022", "04", "02", "18", "03"),
  // },
  // {
  //   id: 1434,
  //   name: "Fried Rice",
  //   amount: 4,
  //   price: 219,
  //   type: "veg",
  //   cuisine: "North-Indian",
  //   orderDate: new Date("2022", "05", "02", "18", "03"),
  // },
  // {
  //   id: 1479,
  //   name: "Pasta",
  //   amount: 3,
  //   price: 209,
  //   type: "non-veg",
  //   cuisine: "South-Indian",
  //   orderDate: new Date("2022", "06", "22", "18", "03"),
  // },
  // {
  //   id: 14756,
  //   name: "Plain rice",
  //   amount: 3,
  //   price: 29,
  //   type: "veg",
  //   cuisine: "South-Indian",
  //   orderDate: new Date("2022", "09", "05", "18", "03"),
  // },
  // {
  //   id: 1476666,
  //   name: "kebab",
  //   amount: 3,
  //   price: 249,
  //   type: "non-veg",
  //   cuisine: "North-Indian",
  //   orderDate: new Date("2022", "08", "02", "18", "03"),
  // },
  // {
  //   id: 147457,
  //   name: "Lemon Chicken",
  //   amount: 3,
  //   price: 549,
  //   type: "non-veg",
  //   cuisine: "South-Indian",
  //   orderDate: new Date("2022", "09", "08", "18", "03"),
  // },
];
